import Head from "next/head";
import Hero from "@/components/home/Hero";
import Partners from "@/components/home/Partners";
import Features from "@/components/home/Features";
import Review from "@/components/home/Review";
import CTA from "@/components/home/CTA";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pedersen Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-900">
        <Hero />
        <Partners />
        <Features />
        <Review />
        <CTA />
      </main>
    </>
  );
}
